language: java
jdk:
    - openjdk8
    - openjdk9
cache: bundler
addons:
  sonarcloud:
    organization: valentino7
    token: e242c9ef44eb9e3732508da0e6c876ae2630577c
install: mvn -X clean package -DskipTests
script: mvn -X clean verify


