language: java
jdk:
    - openjdk8    
addons:
  sonarcloud:
    organization: "valentino7"
    token:
      secure: "c95bf27bd8bc8521c9e42fe5133cb480d87fb8a0"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
